# Generated by Django 4.2.16 on 2024-12-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_rename_category_category_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='social_links',
            field=models.URLField(default='https://example.com'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video_links',
            field=models.URLField(default='https://example.com'),
        ),
        migrations.AlterField(
            model_name='post',
            name='web_links',
            field=models.URLField(default='https://example.com'),
        ),
    ]
